### ISSUE TITLE
question about monad

### ISSUE THREAD

**Issue by aa755** [rems-project/sail-arm#2]
In the POL2019 paper, in Sec. 4.2, you describe the following monad:
````
type monad 'r 'a 'e =
| Done of 'a
| Read_mem of read_kind * address * nat * (list mem_byte -> monad 'r 'a 'e)
| Write_ea of write_kind * address * nat * monad 'r 'a 'e
| Write_memv of list mem_byte * (bool -> monad 'r 'a 'e)
...
| Barrier of barrier_kind * monad 'r 'a 'e
| Read_reg of register_name * ('r -> monad 'r 'a 'e)
| Write_reg of register_name * 'r * monad 'r 'a 'e
| Undefined of (bool -> monad 'r 'a 'e)
| Exception of 'e (* Exception thrown *)
````
Can you please confirm that the type `address` denotes physical address (not virtual addresses)?
Also, is that monad transcribed [here](https://github.com/rems-project/sail-arm/blob/3e9543dd97ebb99024ae04a6978428d956ab099e/arm-v8.5-a/snapshots/coq/lib/Sail2_prompt_monad.v#L11) in Coq?

**Comment by bauereiss** [comment]
> Can you please confirm that the type `address` denotes physical address (not virtual addresses)?

Yes, address translation is part of the specification, so the addresses that end up in the memory reading/writing outcomes of the monad are physical addresses.

> Also, is that monad transcribed [here](https://github.com/rems-project/sail-arm/blob/3e9543dd97ebb99024ae04a6978428d956ab099e/arm-v8.5-a/snapshots/coq/lib/Sail2_prompt_monad.v#L11) in Coq?

Yes, that's the monad.  There is also a state monad, and a lifting from the former to the latter in `Sail2_state_lifting.v`.  (Please correct me if I'm wrong, @bacam.)

Are you planning on using the Coq definitions generated from the model?

**Comment by aa755** [comment]
Thanks. I was just trying to understand how address translation works on ARM: in particular, how the MMU actions of multiple cores interleave. Your approach to modeling interleavings is interesting.
We do hope to eventually use your Coq definitions when we formally connect everything and minimize our TCB.

**Comment by PeterSewell** [comment]
On Tue, 31 Dec 2019 at 01:29, Abhishek Anand <notifications@github.com>
wrote:

> Thanks. I was just trying to understand how address translation works on
> ARM: in particular, how the MMU actions of multiple cores interleave. Your
> approach to modeling interleavings is interesting.
> We do hope to eventually use your Coq definitions when we formally connect
> everything and minimize our TCB.
>
Note that the Sail ISA model alone only captures the in-order behaviour,
from Arm's ASL.  The allowed out-of-order accesses and caching for MMU
behaviour is something that we're looking at.

Also worth noting that some of the other Sail models don't cover address
translation; in those, the monad addresses are effectively virtual
addresses.

Peter
