### ISSUE TITLE
Bugs in ARM-v9.4-A specification?

### ISSUE THREAD

**Issue by soomin-kim** [rems-project/sail-arm#20]
Hello,

I have noticed that the Sail specification for the USAT instruction (and similar instructions) in the AArch32 instruction set of ARM-v9.4-a seems to differ from the manual.
Referencing [this link](https://github.com/rems-project/sail-arm/blob/master/arm-v9.4-a/src/instrs32.sail#L18595), there is the following assertion:

```
    assert(constraint(0 <= 'saturate_to - 1));
```
This assertion imposes an additional condition, requiring the `'saturate_to` variable to be greater than or equal to 1, which is not present in the [ARM manual](https://developer.arm.com/documentation/ddi0597/2024-03/Base-Instructions/USAT--Unsigned-Saturate-?lang=en). It appears this was added to prevent accessing a bitvector at index `N-1` in the `ZeroUnsignedSatQ` function.
However, this assertion prevents the valid case from being considered where `'saturate_to` is 0. Is there a way to resolve this issue?

Thank you.

**Comment by bacam** [comment]
Thanks for reporting this.  It's attempting to avoid a zero-length assignment, and needs a small tweak to handle this case.  I'll try to get that done today.

**Comment by bacam** [comment]
That should work now.

**Comment by soomin-kim** [comment]
Thank you for the quick fix!
